server:
  connection-time-out:
    seconds: 7
  write-time-out:
    seconds: 5
  port: 8080

instance:
  name: load-balance

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
