server:
  connection-time-out:
    seconds: 7
  write-time-out:
    seconds: 5
  port: 8080

spring:
  data:
    redis:
      host: redis-cache
      port: 6379
  application:
    name: load-balancer

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
