server:
  connection-time-out:
    seconds: 7
  write-time-out:
    seconds: 5
  port: 8080

spring:
  data:
    redis:
      host: redis-cache
      port: 6379
  application:
    name: load-balancer


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        failureRateThreshold: 10
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
      testCircuitBreaker:
        baseConfig: default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      showDetails: always
    web:
      exposure:
        include: "*"
      expose: "*"
    metrics:
      enabled: true
  metrics:
    enable:
      resilience4j:
        circuitbreaker:
          calls: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
